// Code generated by MockGen. DO NOT EDIT.
// Source: service/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "customer/models"
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockHandlerIn is a mock of HandlerIn interface.
type MockHandlerIn struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerInMockRecorder
}

// MockHandlerInMockRecorder is the mock recorder for MockHandlerIn.
type MockHandlerInMockRecorder struct {
	mock *MockHandlerIn
}

// NewMockHandlerIn creates a new mock instance.
func NewMockHandlerIn(ctrl *gomock.Controller) *MockHandlerIn {
	mock := &MockHandlerIn{ctrl: ctrl}
	mock.recorder = &MockHandlerInMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerIn) EXPECT() *MockHandlerInMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHandlerIn) Create(ctx *gofr.Context, customer models.Customer) (models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, customer)
	ret0, _ := ret[0].(models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHandlerInMockRecorder) Create(ctx, customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHandlerIn)(nil).Create), ctx, customer)
}

// Delete mocks base method.
func (m *MockHandlerIn) Delete(ctx *gofr.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHandlerInMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHandlerIn)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockHandlerIn) Get(ctx *gofr.Context) ([]models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHandlerInMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHandlerIn)(nil).Get), ctx)
}

// GetByID mocks base method.
func (m *MockHandlerIn) GetByID(ctx *gofr.Context, id int) (models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHandlerInMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHandlerIn)(nil).GetByID), ctx, id)
}

// Patch mocks base method.
func (m *MockHandlerIn) Patch(ctx *gofr.Context, id int, customer models.Customer) (models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, id, customer)
	ret0, _ := ret[0].(models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockHandlerInMockRecorder) Patch(ctx, id, customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHandlerIn)(nil).Patch), ctx, id, customer)
}

// Update mocks base method.
func (m *MockHandlerIn) Update(ctx *gofr.Context, customer models.Customer) (models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, customer)
	ret0, _ := ret[0].(models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockHandlerInMockRecorder) Update(ctx, customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHandlerIn)(nil).Update), ctx, customer)
}
